# Generated by Django 3.1.7 on 2021-05-26 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dvf', '0006_auto_20210503_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=255, null=True)),
                ('picture_url', models.CharField(max_length=255, null=True)),
                ('agent', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website_url', models.CharField(max_length=255, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvf.commune')),
            ],
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['commune'], name='agencies_ag_commune_aa8db8_idx'),
        ),
    ]
