# Generated by Django 3.1.7 on 2021-05-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0002_auto_20210526_2314"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "Agencies"},
        ),
        migrations.RemoveField(
            model_name="agency",
            name="code_postal",
        ),
        migrations.AlterField(
            model_name="agency",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
