# Generated by Django 3.1.7 on 2021-12-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_tench'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tench',
            old_name='tench_name',
            new_name='price_range',
        ),
    ]
