# Generated by Django 3.1.7 on 2021-12-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_auto_20211202_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tench',
            new_name='Pricing',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='max_inhabitant',
            new_name='max_population',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='min_inhabitant',
            new_name='min_population',
        ),
    ]
