# Generated by Django 3.1.7 on 2022-02-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("agencies", "0006_auto_20211203_1435")]

    operations = [migrations.RenameField(model_name="pricing", old_name="price_range", new_name="name")]
