# Generated by Django 3.1.7 on 2022-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("agencies", "0008_auto_20220209_1346")]

    operations = [
        migrations.RemoveIndex(model_name="agency", name="agencies_ag_code_co_d6edf8_idx"),
        migrations.AlterField(
            model_name="agency", name="code_commune", field=models.CharField(max_length=255, null=True)
        ),
        migrations.AddIndex(
            model_name="agency", index=models.Index(fields=["code_commune"], name="agencies_ag_code_co_852095_idx")
        ),
    ]
