# Generated by Django 3.1.7 on 2022-02-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dvf", "0010_auto_20220203_0056"), ("agencies", "0009_auto_20220209_1426")]

    operations = [
        migrations.RemoveIndex(model_name="agency", name="agencies_ag_code_co_852095_idx"),
        migrations.AlterField(
            model_name="agency",
            name="code_commune",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="dvf.commune"),
        ),
        migrations.AddIndex(
            model_name="agency", index=models.Index(fields=["code_commune"], name="agencies_ag_code_co_d6edf8_idx")
        ),
    ]
