# Generated by Django 3.1.7 on 2022-02-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dvf", "0010_auto_20220203_0056"), ("agencies", "0010_auto_20220209_1428")]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="code_commune",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="cities_owned", to="dvf.commune"
            ),
        )
    ]
