# Generated by Django 3.1.7 on 2022-02-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dvf", "0010_auto_20220203_0056"), ("agencies", "0011_auto_20220209_1439")]

    operations = [
        migrations.RemoveIndex(model_name="agency", name="agencies_ag_code_co_d6edf8_idx"),
        migrations.RemoveField(model_name="agency", name="code_commune"),
        migrations.AddField(
            model_name="agency",
            name="commune",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="communes", to="dvf.commune"
            ),
        ),
    ]
