# Generated by Django 3.1.7 on 2022-02-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("agencies", "0012_auto_20220209_1453")]

    operations = [migrations.RemoveField(model_name="agency", name="commune")]
