# Generated by Django 3.1.7 on 2021-10-27 14:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0002_auto_20211027_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
