# Generated by Django 3.1.7 on 2021-10-27 15:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iris", "0003_auto_20211027_1449")]

    operations = [
        migrations.AlterField(
            model_name="iris", name="geometry", field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=2154)
        )
    ]
