# Generated by Django 3.1.7 on 2022-02-17 21:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0005_auto_20220217_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='geometry_4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='iris',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=2154),
        ),
    ]
