# Generated by Django 3.1.7 on 2021-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValeursFoncieres",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("id_mutation", models.CharField(max_length=255, null=True)),
                ("date_mutation", models.DateField(null=True)),
                ("numero_disposition", models.IntegerField(null=True)),
                ("nature_mutation", models.CharField(max_length=255, null=True)),
                (
                    "valeur_fonciere",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("adresse_numero", models.IntegerField(null=True)),
                ("adresse_suffixe", models.CharField(max_length=255, null=True)),
                ("adresse_nom_voie", models.CharField(max_length=255, null=True)),
                ("adresse_code_voie", models.CharField(max_length=255, null=True)),
                ("code_postal", models.CharField(max_length=255, null=True)),
                ("code_commune", models.CharField(max_length=255, null=True)),
                ("nom_commune", models.CharField(max_length=255, null=True)),
                ("code_departement", models.CharField(max_length=255, null=True)),
                ("ancien_code_commune", models.CharField(max_length=255, null=True)),
                ("ancien_nom_commune", models.CharField(max_length=255, null=True)),
                ("id_parcelle", models.CharField(max_length=255, null=True)),
                ("ancien_id_parcelle", models.CharField(max_length=255, null=True)),
                ("numero_volume", models.CharField(max_length=255, null=True)),
                ("lot1_numero", models.CharField(max_length=255, null=True)),
                (
                    "lot1_surface_carrez",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("lot2_numero", models.CharField(max_length=255, null=True)),
                (
                    "lot2_surface_carrez",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("lot3_numero", models.CharField(max_length=255, null=True)),
                (
                    "lot3_surface_carrez",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("lot4_numero", models.CharField(max_length=255, null=True)),
                (
                    "lot4_surface_carrez",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("lot5_numero", models.CharField(max_length=255, null=True)),
                (
                    "lot5_surface_carrez",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("nombre_lots", models.IntegerField(null=True)),
                ("code_type_local", models.CharField(max_length=255, null=True)),
                ("type_local", models.CharField(max_length=255, null=True)),
                (
                    "surface_reelle_bati",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("nombre_pieces_principales", models.IntegerField(null=True)),
                ("code_nature_culture", models.CharField(max_length=255, null=True)),
                ("nature_culture", models.CharField(max_length=255, null=True)),
                (
                    "code_nature_culture_speciale",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "nature_culture_speciale",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "surface_terrain",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("section_prefixe", models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="valeursfoncieres",
            index=models.Index(
                fields=["date_mutation", "code_commune", "type_local"],
                name="dvf_valeurs_date_mu_c781de_idx",
            ),
        ),
    ]
