# Generated by Django 3.1.7 on 2021-04-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvf', '0003_auto_20210412_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeursfoncieres',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
