# Generated by Django 3.1.7 on 2021-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvf', '0008_auto_20210612_1840'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='valeursfoncieres',
            name='dvf_valeurs_date_mu_d6c4a7_idx',
        ),
        migrations.AddIndex(
            model_name='valeursfoncieres',
            index=models.Index(fields=['code_commune', 'type_local', 'date_mutation', 'longitude', 'latitude'], name='dvf_valeurs_code_co_3083a4_idx'),
        ),
    ]
