# Generated by Django 3.1.7 on 2022-02-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("agencies", "0013_remove_agency_commune"), ("dvf", "0010_auto_20220203_0056")]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="agency",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="agencies", to="agencies.agency"
            ),
        )
    ]
