# Generated by Django 3.1.7 on 2022-02-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0004_auto_20211027_1508'),
        ('dvf', '0010_auto_20220203_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeursfoncieres',
            name='code_iris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iris.iris'),
        ),
    ]
