# Generated by Django 3.1.7 on 2022-02-03 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0004_auto_20211027_1508'),
        ('dvf', '0011_valeursfoncieres_code_iris'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mutationiris',
            name='dvf_mutatio_id_muta_8487de_idx',
        ),
        migrations.RemoveIndex(
            model_name='mutationiris',
            name='dvf_mutatio_code_ir_89f8d4_idx',
        ),
        migrations.AlterField(
            model_name='mutationiris',
            name='code_iris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iris.iris'),
        ),
        migrations.AlterField(
            model_name='mutationiris',
            name='id_mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvf.valeursfoncieres'),
        ),
        migrations.RemoveField(
            model_name='valeursfoncieres',
            name='code_iris',
        ),
        migrations.AddField(
            model_name='valeursfoncieres',
            name='code_iris',
            field=models.ManyToManyField(null=True, through='dvf.MutationIris', to='iris.IRIS'),
        ),
        migrations.AddIndex(
            model_name='mutationiris',
            index=models.Index(fields=['id_mutation'], name='dvf_mutatio_id_muta_58ed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='mutationiris',
            index=models.Index(fields=['code_iris'], name='dvf_mutatio_code_ir_a15e63_idx'),
        ),
    ]
