# Generated by Django 3.1.7 on 2022-02-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("agencies", "0013_remove_agency_commune"), ("dvf", "0011_commune_agency")]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="agency",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="agencies.agency"),
        )
    ]
