# Generated by Django 3.1.7 on 2022-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvf', '0012_auto_20220225_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneVoisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal_a', models.CharField(max_length=255)),
                ('code_postal_b', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='communevoisine',
            index=models.Index(fields=['code_postal_a'], name='dvf_commune_code_po_9e234b_idx'),
        ),
    ]
