# Generated by Django 3.1.7 on 2022-02-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvf', '0012_auto_20220203_0119'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mutationiris',
            name='dvf_mutatio_id_muta_58ed4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='mutationiris',
            name='dvf_mutatio_code_ir_a15e63_idx',
        ),
        migrations.RemoveField(
            model_name='valeursfoncieres',
            name='code_iris',
        ),
        migrations.AlterField(
            model_name='mutationiris',
            name='code_iris',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mutationiris',
            name='id_mutation',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='mutationiris',
            index=models.Index(fields=['id_mutation'], name='dvf_mutatio_id_muta_8487de_idx'),
        ),
        migrations.AddIndex(
            model_name='mutationiris',
            index=models.Index(fields=['code_iris'], name='dvf_mutatio_code_ir_89f8d4_idx'),
        ),
    ]
